# Generated by Django 4.0.6 on 2022-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('User', 'User'), ('Coordinator', 'Coordinator')], default='User', max_length=12),
        ),
    ]
